# GitHub Sponsors
github: [ghoshsurya]

# Other platforms
patreon: codesplex
ko_fi: codesplex
buy_me_a_coffee: codesplex

# Custom URLs
custom: ['https://codesplex.com/sponsor', 'https://paypal.me/codesplex']