[build]
  publish = "frontend/build"
  command = "cd frontend && npm install && npm run build && cd ../netlify/functions && npm install"

[build.environment]
  NODE_VERSION = "18"
  # Add these environment variables in Netlify dashboard:
  # REACT_APP_AUTH0_DOMAIN
  # REACT_APP_AUTH0_CLIENT_ID
  # REACT_APP_AUTH0_AUDIENCE
  # DATABASE_URL (Neon connection string)
  # AUTH0_DOMAIN
  # AUTH0_AUDIENCE

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/neon-api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"